"""Generic example scenario (John & Jane Smith) — mirrors the source model defaults."""

DEFAULT_SCENARIO = {
    "household": {
        "client_name": "John Smith",
        "client_dob_year": 1965,
        "client_life_expectancy": 90,
        "spouse_name": "Jane Smith",
        "spouse_dob_year": 1966,
        "spouse_life_expectancy": 92,
        "filing_status": "Married Filing Jointly",
    },
    "projection": {
        "start_year": 2026,
        "end_year": 2058,
        "general_inflation": 0.03,
        "bracket_indexing": 0.03,
        "irmaa_indexing": 0.03,
    },
    "income_streams": [
        {"id": "WAG01", "owner": "Client", "type": "Wages", "description": "Client Wages",
         "start_year": 2026, "stop_year": 2027, "amount": 350000, "frequency": "Annual",
         "cola": 0.03, "tax_character": "Ordinary", "taxable_pct": 1.0, "survivor_pct": 0.0, "use": True},
        {"id": "SS01", "owner": "Client", "type": "Social Security", "description": "Client SS @ claim",
         "start_year": 2032, "stop_year": None, "amount": 4152, "frequency": "Monthly",
         "cola": 0.03, "tax_character": "SS", "taxable_pct": 0.0, "survivor_pct": 1.0, "use": True},
        {"id": "SS02", "owner": "Spouse", "type": "Social Security", "description": "Spouse SS @ claim",
         "start_year": 2028, "stop_year": None, "amount": 2906, "frequency": "Monthly",
         "cola": 0.03, "tax_character": "SS", "taxable_pct": 0.0, "survivor_pct": 1.0, "use": True},
        {"id": "PEN01", "owner": "Client", "type": "Pension", "description": "Client Pension",
         "start_year": 2027, "stop_year": None, "amount": 4500, "frequency": "Monthly",
         "cola": 0.04, "tax_character": "Ordinary", "taxable_pct": 1.0, "survivor_pct": 0.5, "use": True},
        {"id": "DIV03", "owner": "Joint", "type": "Dividend/LTCG", "description": "Joint Dividends & Realized LTCG",
         "start_year": 2026, "stop_year": None, "amount": 150000, "frequency": "Annual",
         "cola": 0.03, "tax_character": "QDiv/LTCG", "taxable_pct": 1.0, "survivor_pct": 1.0, "use": True},
    ],
    "expenses": [
        {"id": "EXP01", "owner": "Joint", "category": "Living Expenses", "start_year": 2026,
         "stop_year": None, "amount": 180000, "frequency": "Annual", "inflation": 0.03, "use": True},
        {"id": "EXP02", "owner": "Joint", "category": "Medical", "start_year": 2026,
         "stop_year": None, "amount": 1500, "frequency": "Monthly", "inflation": 0.06, "use": True},
        {"id": "EXP07", "owner": "Joint", "category": "Travel / Discretionary", "start_year": 2026,
         "stop_year": None, "amount": 20000, "frequency": "Annual", "inflation": 0.04, "use": True},
    ],
    "accounts": [
        {"id": "CASH", "owner": "Joint", "name": "Cash / Checking", "tax_type": "Cash",
         "beginning_balance": 100000, "cost_basis": 0, "return": 0.03},
        {"id": "TAXC", "owner": "Client", "name": "Client Taxable Brokerage", "tax_type": "Taxable",
         "beginning_balance": 3000000, "cost_basis": 1000000, "return": 0.07},
        {"id": "TAXS", "owner": "Spouse", "name": "Spouse Taxable Brokerage", "tax_type": "Taxable",
         "beginning_balance": 3000000, "cost_basis": 1000000, "return": 0.07},
        {"id": "IRAC", "owner": "Client", "name": "Client Trad IRA / 401(k)", "tax_type": "Tax-Deferred",
         "beginning_balance": 3850000, "cost_basis": 0, "return": 0.07},
        {"id": "IRAS", "owner": "Spouse", "name": "Spouse Trad IRA / 401(k)", "tax_type": "Tax-Deferred",
         "beginning_balance": 1150000, "cost_basis": 0, "return": 0.07},
        {"id": "ROTC", "owner": "Client", "name": "Client Roth IRA", "tax_type": "Tax-Free",
         "beginning_balance": 0, "cost_basis": 0, "return": 0.07},
        {"id": "ROTS", "owner": "Spouse", "name": "Spouse Roth IRA", "tax_type": "Tax-Free",
         "beginning_balance": 0, "cost_basis": 0, "return": 0.07},
        {"id": "HOME", "owner": "Joint", "name": "Primary Residence", "tax_type": "Real Estate",
         "beginning_balance": 1000000, "cost_basis": 0, "return": 0.035},
    ],
    "tax": {
        "state_rate": 0.0399,
        "include_irmaa": True,
        "survivor_filing_status": "Single",
        "survivor_spending_reduction": 0.2,
    },
    "roth": {
        "enabled": True,
        "start_year": 2026,
        "end_year": 2058,
        "target_bracket": 0.24,
        "max_annual": 0.0,
        "stop_at_rmd_age": True,
    },
    "dividend_yield": 0.02,
    "mortgage_balance": 0,
    "withdrawal": {
        "funding_order": "Cash → Taxable → IRA → Roth",
        "ira_split": 0.5,
    },
    "legacy": {
        "estate_settlement_pct": 0.01,
        "heir_federal_rate": 0.24,
        "heir_state_rate": 0.06,
        "step_up_at_death": True,
    },
}
